---
name: "Deploy to QuantCDN"

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn

      - name: Build static output
        run: yarn build

      - name: Deploy updates to QuantCDN
        uses: quantcdn/deploy-action@v1.3.3
        with:
          customer: ${{ secrets.QUANT_CUSTOMER_ID }}
          project: ${{ secrets.QUANT_PROJECT_ID }}
          token: ${{ secrets.QUANT_TOKEN }}
          endpoint: ${{ secrets.QUANT_ENDPOINT || 'https://api.quantcdn.io' }}
          dir: build
          chunk-size: 20
          skip-purge: true

      - name: Purge the QuantCDN cache
        uses: quantcdn/purge-action@v1.2.1
        with:
          customer: ${{ secrets.QUANT_CUSTOMER_ID }}
          project: ${{ secrets.QUANT_PROJECT_ID }}
          token: ${{ secrets.QUANT_TOKEN }}
          endpoint: ${{ secrets.QUANT_ENDPOINT || 'https://api.quantcdn.io' }}
          url_pattern: "/*"

