name: Test

on:
  - push

env:
  NODE_ENV: development

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --dev

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run test
